# Generated by Django 3.0.3 on 2020-05-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appecom', '0002_auto_20200520_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
