# Generated by Django 3.0.3 on 2020-05-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appecom', '0005_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='max_price',
        ),
        migrations.AddField(
            model_name='product',
            name='cuosines',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='year_since',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
