# Generated by Django 3.0.3 on 2020-05-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appecom', '0006_auto_20200522_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
