# Generated by Django 3.0.3 on 2020-05-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appecom', '0007_product_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
