# Generated by Django 3.0.3 on 2020-05-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appecom', '0008_auto_20200522_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
