# Generated by Django 3.0.3 on 2020-05-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appecom', '0009_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/pics'),
        ),
    ]
